#!/bin/zsh

launchd_plist_name='com.company.itops.mdm_check'

/bin/mkdir -p "/Library/CPE/Logs"
/bin/chmod -R 777 "/Library/CPE/Logs"

if /bin/launchctl list $launchd_plist_name &> /dev/null; then
    /bin/echo "Unloading previous mdm_check job..."
    /bin/launchctl bootout system/$launchd_plist_name
fi
/bin/launchctl bootstrap system "/Library/LaunchDaemons/${launchd_plist_name}.plist"
